version: 2

sources:
  - name: DEMO          # logical name you’ll use in SQL
    database: DEMO                 # your Snowflake database
    schema: DEMO_SCHEMA            # schema where raw tables live
    tables:
      - name: WEATHER
      - name: BIKE      # table name in Snowflake
